"""
seed_puzzles_mlb.py — Insert MLB daily puzzles 2026-03-17 through 2026-05-24 (69 days).
Mix of ~40 hitters and ~29 pitchers, including legends. Safe to re-run.

Reveal order philosophy:
  Data-driven via gen_reveals.py mlb (z-score vs position-group peers).
  Pitchers compared to all pitchers (stamina naturally separates SP from RP/CP).
  Catchers get blocking as an extra candidate attribute.
  Slots 1-3: near-average attributes (low |z|, generic).
  Slots 7-8: highest |z| — signature stats that clinch identification.
"""

import sqlite3
import json
import os
import random

DB_PATH = os.environ.get("RATINGSCHECK_DB", "ratingscheck.db")

DATES = [
    "2026-03-17","2026-03-18","2026-03-19","2026-03-20","2026-03-21","2026-03-22","2026-03-23",
    "2026-03-24","2026-03-25","2026-03-26","2026-03-27","2026-03-28","2026-03-29","2026-03-30",
    "2026-03-31","2026-04-01","2026-04-02","2026-04-03","2026-04-04","2026-04-05","2026-04-06",
    "2026-04-07","2026-04-08","2026-04-09","2026-04-10","2026-04-11","2026-04-12","2026-04-13",
    "2026-04-14","2026-04-15","2026-04-16","2026-04-17","2026-04-18","2026-04-19","2026-04-20",
    "2026-04-21","2026-04-22","2026-04-23","2026-04-24","2026-04-25","2026-04-26","2026-04-27",
    "2026-04-28","2026-04-29","2026-04-30","2026-05-01","2026-05-02","2026-05-03","2026-05-04",
    "2026-05-05","2026-05-06","2026-05-07","2026-05-08","2026-05-09","2026-05-10","2026-05-11",
    "2026-05-12","2026-05-13","2026-05-14","2026-05-15","2026-05-16","2026-05-17","2026-05-18",
    "2026-05-19","2026-05-20","2026-05-21","2026-05-22","2026-05-23","2026-05-24",
]

# Exactly 69 players (~40 hitters, ~29 pitchers)
# Reveal orders generated by gen_reveals.py using z-scores vs position-group peers.
PLAYER_REVEALS = [
    # ══ HITTERS ══
    (39, ["speed", "armStrength", "armAccuracy", "fieldingAbility", "plateDiscipline", "powerRight", "powerLeft", "contactLeft"]),  # Albert Pujols 99 1B
    (1403, ["armAccuracy", "fieldingAbility", "armStrength", "plateDiscipline", "speed", "powerLeft", "battingClutch", "powerRight"]),  # Miguel Cabrera 99 3B
    (1874, ["speed", "fieldingAbility", "battingClutch", "contactLeft", "plateVision", "powerRight", "plateDiscipline", "powerLeft"]),  # Troy Tulowitzki 99 SS
    (668, ["armStrength", "plateVision", "speed", "plateDiscipline", "contactRight", "contactLeft", "fieldingAbility", "powerLeft"]),  # Francisco Lindor 95 SS
    (1059, ["armStrength", "plateDiscipline", "speed", "powerRight", "battingClutch", "contactRight", "contactLeft", "plateVision"]),  # Jose Ramirez 95 3B
    (1096, ["fieldingAbility", "armStrength", "speed", "plateVision", "armAccuracy", "powerRight", "battingClutch", "plateDiscipline"]),  # Juan Soto 95 RF
    (272, ["speed", "plateVision", "fieldingAbility", "powerLeft", "contactLeft", "battingClutch", "contactRight", "plateDiscipline"]),  # Bryce Harper 94 RF
    (615, ["plateVision", "armAccuracy", "speed", "plateDiscipline", "fieldingAbility", "battingClutch", "contactLeft", "powerLeft"]),  # Elly De La Cruz 94 SS
    (831, ["armStrength", "powerRight", "powerLeft", "fieldingAbility", "armAccuracy", "battingClutch", "contactRight", "plateVision"]),  # Jackie Robinson 94 2B
    (2001, ["plateDiscipline", "armStrength", "armAccuracy", "plateVision", "speed", "battingClutch", "contactLeft", "powerLeft"]),  # Yordan Alvarez 94 LF
    (1145, ["plateVision", "fieldingAbility", "plateDiscipline", "speed", "contactRight", "armStrength", "contactLeft", "powerLeft"]),  # Ken Griffey Jr. 95 CF
    (1801, ["armStrength", "speed", "fieldingAbility", "powerRight", "powerLeft", "battingClutch", "contactLeft", "plateVision"]),  # Ted Simmons 96 C
    (1037, ["blocking", "plateVision", "speed", "armStrength", "armAccuracy", "battingClutch", "powerRight", "plateDiscipline"]),  # Jorge Posada 94 C
    (1303, ["plateVision", "armStrength", "armAccuracy", "fieldingAbility", "powerLeft", "battingClutch", "contactRight", "plateDiscipline"]),  # Manny Ramirez 94 LF
    (1652, ["speed", "armStrength", "armAccuracy", "contactLeft", "blocking", "powerRight", "contactRight", "battingClutch"]),  # Roy Campanella 94 C
    (521, ["armAccuracy", "armStrength", "fieldingAbility", "plateDiscipline", "powerLeft", "plateVision", "speed", "powerRight"]),  # Daylen Lile 94 LF
    (1460, ["plateVision", "speed", "fieldingAbility", "armAccuracy", "contactLeft", "powerLeft", "contactRight", "plateDiscipline"]),  # Nick Kurtz 94 1B
    (50, ["plateDiscipline", "armStrength", "speed", "battingClutch", "powerRight", "contactRight", "plateVision", "powerLeft"]),  # Alex Bregman 94 3B
    (461, ["armStrength", "fieldingAbility", "powerRight", "armAccuracy", "speed", "plateVision", "plateDiscipline", "contactLeft"]),  # Craig Biggio 94 2B
    (9, ["fieldingAbility", "speed", "armAccuracy", "armStrength", "contactRight", "battingClutch", "powerRight", "powerLeft"]),  # Aaron Judge 93 RF
    (190, ["plateDiscipline", "powerLeft", "plateVision", "armStrength", "powerRight", "battingClutch", "armAccuracy", "speed"]),  # Bobby Witt Jr. 93 SS
    (511, ["contactLeft", "battingClutch", "speed", "fieldingAbility", "powerLeft", "plateDiscipline", "armAccuracy", "powerRight"]),  # David Ortiz 93 1B
    (674, ["fieldingAbility", "armStrength", "plateVision", "contactLeft", "speed", "armAccuracy", "powerLeft", "battingClutch"]),  # Freddie Freeman 93 1B
    (716, ["armAccuracy", "armStrength", "fieldingAbility", "plateVision", "contactRight", "contactLeft", "plateDiscipline", "powerLeft"]),  # Giancarlo Stanton 93 LF
    (950, ["speed", "plateDiscipline", "battingClutch", "fieldingAbility", "contactRight", "powerRight", "armStrength", "armAccuracy"]),  # Jim Rice 93 LF
    (954, ["plateDiscipline", "powerRight", "powerLeft", "contactRight", "battingClutch", "armStrength", "armAccuracy", "fieldingAbility"]),  # Jimmy Rollins 93 SS
    (1302, ["plateDiscipline", "contactLeft", "contactRight", "plateVision", "powerRight", "battingClutch", "armAccuracy", "powerLeft"]),  # Manny Machado 93 3B
    (1346, ["plateVision", "armStrength", "plateDiscipline", "battingClutch", "contactLeft", "fieldingAbility", "speed", "powerRight"]),  # Matt Olson 93 1B
    (1399, ["plateVision", "fieldingAbility", "speed", "contactRight", "battingClutch", "armStrength", "powerRight", "plateDiscipline"]),  # Mickey Mantle 93 CF
    (1840, ["armAccuracy", "fieldingAbility", "armStrength", "plateVision", "powerRight", "powerLeft", "battingClutch", "plateDiscipline"]),  # Travis Bazzana 93 2B
    (1934, ["speed", "fieldingAbility", "plateDiscipline", "powerRight", "battingClutch", "plateVision", "contactLeft", "armStrength"]),  # Vladimir Guerrero Sr. 93 RF
    (1935, ["armStrength", "fieldingAbility", "armAccuracy", "speed", "plateDiscipline", "contactLeft", "powerLeft", "contactRight"]),  # Vladimir Guerrero Jr. 93 1B
    (324, ["speed", "armStrength", "contactRight", "armAccuracy", "fieldingAbility", "plateVision", "contactLeft", "plateDiscipline"]),  # Carlos Santana 95 1B
    (412, ["armAccuracy", "speed", "fieldingAbility", "powerRight", "armStrength", "powerLeft", "battingClutch", "plateDiscipline"]),  # Cody Bellinger 93 CF
    (574, ["powerLeft", "armStrength", "powerRight", "speed", "plateDiscipline", "fieldingAbility", "battingClutch", "contactLeft"]),  # Dustin Pedroia 93 2B
    (717, ["armAccuracy", "speed", "armStrength", "plateDiscipline", "powerRight", "fieldingAbility", "contactLeft", "plateVision"]),  # Gil Hodges 93 1B
    (1043, ["plateVision", "fieldingAbility", "speed", "contactRight", "battingClutch", "contactLeft", "powerRight", "plateDiscipline"]),  # Jose Bautista 93 RF
    (1697, ["armStrength", "speed", "blocking", "contactRight", "contactLeft", "fieldingAbility", "battingClutch", "armAccuracy"]),  # Salvador Perez 93 C
    (1985, ["powerRight", "speed", "plateDiscipline", "fieldingAbility", "armStrength", "plateVision", "battingClutch", "contactLeft"]),  # Yandy Diaz 93 1B
    (1, ["armAccuracy", "powerLeft", "plateVision", "armStrength", "powerRight", "contactRight", "battingClutch", "plateDiscipline"]),  # A.J. Ewing 92 CF
    # ══ PITCHERS ══
    (660, ["speed", "pitchMovement", "pitchVelocity", "fieldingAbility", "pitchingClutch", "hrPerBf", "stamina", "pitchControl"]),  # Felix Hernandez 99 SP
    (128, ["bbPerBf", "speed", "stamina", "pitchControl", "pitchMovement", "hrPerBf", "fieldingAbility", "pitchingClutch"]),  # Aroldis Chapman 94 CP
    (383, ["fieldingAbility", "pitchVelocity", "hrPerBf", "pitchMovement", "speed", "stamina", "pitchControl", "pitchingClutch"]),  # Chris Sale 94 SP
    (454, ["speed", "fieldingAbility", "pitchControl", "bbPerBf", "pitchMovement", "stamina", "hrPerBf", "pitchingClutch"]),  # Corbin Burnes 94 SP
    (1653, ["pitchVelocity", "pitchMovement", "fieldingAbility", "speed", "pitchingClutch", "stamina", "bbPerBf", "pitchControl"]),  # Roy Halladay 94 SP
    (1747, ["pitchMovement", "pitchingClutch", "pitchControl", "bbPerBf", "fieldingAbility", "pitchVelocity", "hrPerBf", "speed"]),  # Shohei Ohtani 94 SP
    (5, ["speed", "bbPerBf", "fieldingAbility", "pitchControl", "stamina", "pitchVelocity", "pitchingClutch", "hrPerBf"]),  # Aaron Ashby 94 RP
    (111, ["pitchVelocity", "speed", "pitchingClutch", "fieldingAbility", "pitchMovement", "stamina", "pitchControl", "hrPerBf"]),  # Anibal Sanchez 94 SP
    (185, ["speed", "pitchMovement", "pitchVelocity", "bbPerBf", "pitchControl", "pitchingClutch", "stamina", "fieldingAbility"]),  # Bob Gibson 93 SP
    (307, ["speed", "fieldingAbility", "pitchMovement", "pitchVelocity", "bbPerBf", "stamina", "hrPerBf", "pitchingClutch"]),  # Cam Schlittler 93 SP
    (360, ["hrPerBf", "fieldingAbility", "bbPerBf", "pitchMovement", "pitchControl", "pitchVelocity", "stamina", "pitchingClutch"]),  # Chase Dollander 93 SP
    (856, ["fieldingAbility", "bbPerBf", "pitchMovement", "pitchVelocity", "pitchControl", "hrPerBf", "pitchingClutch", "speed"]),  # Jake Arrieta 93 SP
    (1160, ["fieldingAbility", "speed", "pitchVelocity", "pitchMovement", "pitchingClutch", "bbPerBf", "stamina", "pitchControl"]),  # Kevin Gausman 93 SP
    (1364, ["speed", "pitchMovement", "pitchVelocity", "stamina", "hrPerBf", "bbPerBf", "pitchControl", "fieldingAbility"]),  # Max Fried 93 SP
    (1893, ["fieldingAbility", "hrPerBf", "bbPerBf", "pitchControl", "speed", "pitchVelocity", "pitchingClutch", "stamina"]),  # Tyler Glasnow 93 SP
    (268, ["fieldingAbility", "speed", "hrPerBf", "pitchMovement", "pitchingClutch", "stamina", "bbPerBf", "pitchControl"]),  # Bryan Woo 92 SP
    (342, ["speed", "pitchMovement", "pitchVelocity", "pitchingClutch", "bbPerBf", "pitchControl", "stamina", "fieldingAbility"]),  # CC Sabathia 92 SP
    (659, ["pitchControl", "bbPerBf", "speed", "hrPerBf", "stamina", "pitchVelocity", "fieldingAbility", "pitchingClutch"]),  # Felix Bautista 92 CP
    (1152, ["fieldingAbility", "stamina", "pitchMovement", "bbPerBf", "hrPerBf", "pitchControl", "speed", "pitchingClutch"]),  # Kenley Jansen 92 CP
    (1575, ["hrPerBf", "speed", "fieldingAbility", "pitchMovement", "pitchVelocity", "pitchingClutch", "pitchControl", "stamina"]),  # Randy Johnson 92 SP
    (258, ["fieldingAbility", "pitchVelocity", "speed", "stamina", "pitchMovement", "bbPerBf", "pitchingClutch", "pitchControl"]),  # Bruce Sutter 91 CP
    (779, ["hrPerBf", "bbPerBf", "pitchMovement", "fieldingAbility", "pitchVelocity", "pitchingClutch", "stamina", "speed"]),  # Hunter Brown 91 SP
    (840, ["pitchMovement", "fieldingAbility", "speed", "pitchingClutch", "pitchVelocity", "pitchControl", "stamina", "hrPerBf"]),  # Jacob deGrom 91 SP
    (940, ["speed", "fieldingAbility", "stamina", "pitchMovement", "pitchVelocity", "pitchingClutch", "bbPerBf", "pitchControl"]),  # Jhoan Duran 91 CP
    (1326, ["bbPerBf", "speed", "fieldingAbility", "hrPerBf", "pitchMovement", "pitchVelocity", "pitchControl", "pitchingClutch"]),  # Mason Miller 91 CP
    (1569, ["fieldingAbility", "stamina", "pitchMovement", "pitchVelocity", "speed", "pitchingClutch", "bbPerBf", "pitchControl"]),  # Raisel Iglesias 91 CP
    (1640, ["pitchVelocity", "stamina", "hrPerBf", "pitchMovement", "speed", "bbPerBf", "pitchingClutch", "pitchControl"]),  # Rollie Fingers 91 CP
    (1709, ["fieldingAbility", "speed", "pitchMovement", "pitchVelocity", "bbPerBf", "pitchControl", "stamina", "hrPerBf"]),  # Sandy Alcantara 91 SP
    (1712, ["bbPerBf", "speed", "pitchMovement", "pitchControl", "pitchVelocity", "stamina", "pitchingClutch", "hrPerBf"]),  # Satchel Paige 91 SP
]


def main():
    assert len(PLAYER_REVEALS) == len(DATES), f"{len(PLAYER_REVEALS)} players != {len(DATES)} dates"

    random.seed(42)
    players = list(PLAYER_REVEALS)
    random.shuffle(players)

    puzzles = [(date, pid, rev) for date, (pid, rev) in zip(DATES, players)]

    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    skipped = []
    inserted = []

    for date, player_id, reveal_order in puzzles:
        cur.execute("SELECT player_id, created_by FROM daily_puzzles_mlb WHERE date = ?", (date,))
        existing = cur.fetchone()
        if existing:
            ex_pid, ex_by = existing
            if ex_pid != player_id and ex_by != "seed":
                skipped.append(f"  SKIP {date}: admin-scheduled player_id={ex_pid}")
                continue
        cur.execute(
            "INSERT OR REPLACE INTO daily_puzzles_mlb (date, player_id, reveal_order_json, created_by) VALUES (?,?,?,?)",
            (date, player_id, json.dumps(reveal_order), "seed")
        )
        inserted.append(date)

    conn.commit()
    conn.close()

    print(f"Inserted/updated {len(inserted)} puzzles.")
    if skipped:
        print(f"Skipped {len(skipped)} dates (different player already scheduled):")
        for s in skipped:
            print(s)
    print(f"Date range: {puzzles[0][0]} to {puzzles[-1][0]}")
    print("Done.")


if __name__ == "__main__":
    main()
