"""
seed_puzzles_nhl.py — Insert NHL daily puzzles 2026-03-17 through 2026-05-24 (69 days).
Goalies excluded (goalie-specific stats are unpopulated in DB).
Safe to re-run: uses INSERT OR REPLACE. Player order is randomized.

Reveal order philosophy:
  Data-driven via gen_reveals.py nhl (z-score vs position-group peers).
  Slots 1-3: near-average attributes (low |z|, generic).
  Slots 7-8: highest |z| — signature stats that clinch identification.
"""

import sqlite3
import json
import os
import random

DB_PATH = os.environ.get("RATINGSCHECK_DB", "ratingscheck.db")

DATES = [
    "2026-03-17","2026-03-18","2026-03-19","2026-03-20","2026-03-21","2026-03-22","2026-03-23",
    "2026-03-24","2026-03-25","2026-03-26","2026-03-27","2026-03-28","2026-03-29","2026-03-30",
    "2026-03-31","2026-04-01","2026-04-02","2026-04-03","2026-04-04","2026-04-05","2026-04-06",
    "2026-04-07","2026-04-08","2026-04-09","2026-04-10","2026-04-11","2026-04-12","2026-04-13",
    "2026-04-14","2026-04-15","2026-04-16","2026-04-17","2026-04-18","2026-04-19","2026-04-20",
    "2026-04-21","2026-04-22","2026-04-23","2026-04-24","2026-04-25","2026-04-26","2026-04-27",
    "2026-04-28","2026-04-29","2026-04-30","2026-05-01","2026-05-02","2026-05-03","2026-05-04",
    "2026-05-05","2026-05-06","2026-05-07","2026-05-08","2026-05-09","2026-05-10","2026-05-11",
    "2026-05-12","2026-05-13","2026-05-14","2026-05-15","2026-05-16","2026-05-17","2026-05-18",
    "2026-05-19","2026-05-20","2026-05-21","2026-05-22","2026-05-23","2026-05-24",
]

# (player_id, reveal_order) — order is pre-shuffle; main() shuffles with seed 42
# Reveal orders generated by gen_reveals.py using z-scores vs position-group peers.
PLAYER_REVEALS = [
    (278, ["bodyChecking", "fighting", "strength", "slapShotPow", "offAwareness", "deking", "handEye", "agility"]),  # Connor McDavid 97 C EDM
    (173, ["bodyChecking", "fighting", "stickChecking", "handEye", "slapShotPow", "passAcc", "agility", "acceleration"]),  # Nathan Mackinnon 96 C/RW COL
    (279, ["bodyChecking", "fighting", "stickChecking", "strength", "faceoffs", "acceleration", "offAwareness", "wristShotPow"]),  # Leon Draisaitl 96 C EDM
    (716, ["bodyChecking", "strength", "fighting", "slapShotAcc", "acceleration", "slapShotPow", "handEye", "agility"]),  # Nikita Kucherov 96 RW TBL
    (174, ["bodyChecking", "strength", "shotBlocking", "fighting", "deking", "puckControl", "acceleration", "slapShotPow"]),  # Cale Makar 95 RD COL
    (307, ["speed", "bodyChecking", "fighting", "slapShotPow", "strength", "puckControl", "handEye", "defAwareness"]),  # Aleksander Barkov 95 C FLA
    (365, ["shotBlocking", "strength", "wristShotPow", "stickChecking", "fighting", "deking", "puckControl", "agility"]),  # Quinn Hughes 95 D MIN
    (32, ["bodyChecking", "strength", "stickChecking", "speed", "puckControl", "slapShotAcc", "deking", "wristShotPow"]),  # David Pastrnak 94 RW BOS
    (366, ["bodyChecking", "faceoffs", "fighting", "slapShotPow", "defAwareness", "passAcc", "wristShotAcc", "wristShotPow"]),  # Kirill Kaprizov 94 LW/RW MIN
    (607, ["bodyChecking", "acceleration", "fighting", "agility", "slapShotAcc", "offAwareness", "puckControl", "handEye"]),  # Sidney Crosby 94 C PIT
    (746, ["bodyChecking", "fighting", "strength", "offAwareness", "agility", "stickChecking", "faceoffs", "wristShotPow"]),  # Auston Matthews 94 C TOR
    (834, ["strength", "stickChecking", "bodyChecking", "handEye", "wristShotAcc", "passAcc", "speed", "acceleration"]),  # Jack Eichel 94 C VGK
    (226, ["faceoffs", "bodyChecking", "stickChecking", "wristShotPow", "acceleration", "agility", "deking", "slapShotPow"]),  # Mikko Rantanen 93 RW/C DAL
    (308, ["acceleration", "speed", "agility", "offAwareness", "strength", "wristShotAcc", "slapShotPow", "handEye"]),  # Matthew Tkachuk 93 LW/RW FLA
    (309, ["speed", "strength", "bodyChecking", "acceleration", "fighting", "slapShotAcc", "puckControl", "wristShotAcc"]),  # Sam Reinhart 93 RW/C FLA
    (449, ["faceoffs", "strength", "bodyChecking", "slapShotAcc", "handEye", "offAwareness", "passAcc", "acceleration"]),  # Jack Hughes 93 C/LW NJD
    (57, ["stickChecking", "fighting", "strength", "slapShotPow", "bodyChecking", "offAwareness", "passAcc", "acceleration"]),  # Rasmus Dahlin 92 D BUF
    (198, ["bodyChecking", "fighting", "wristShotPow", "shotBlocking", "defAwareness", "speed", "passAcc", "stickChecking"]),  # Zach Werenski 92 D CBJ
    (337, ["strength", "stickChecking", "defAwareness", "slapShotPow", "speed", "wristShotAcc", "offAwareness", "acceleration"]),  # Artemi Panarin 92 LW LAK
    (428, ["bodyChecking", "fighting", "strength", "stickChecking", "defAwareness", "offAwareness", "puckControl", "agility"]),  # Roman Josi 92 LD NSH
    (718, ["strength", "defAwareness", "bodyChecking", "faceoffs", "stickChecking", "handEye", "deking", "speed"]),  # Brayden Point 92 C/RW TBL
    (719, ["shotBlocking", "stickChecking", "fighting", "speed", "wristShotPow", "acceleration", "defAwareness", "slapShotPow"]),  # Victor Hedman 92 LD TBL
    (747, ["stickChecking", "strength", "defAwareness", "wristShotPow", "slapShotPow", "offAwareness", "passAcc", "agility"]),  # William Nylander 92 RW/C TOR
    (835, ["wristShotPow", "strength", "slapShotPow", "faceoffs", "acceleration", "offAwareness", "puckControl", "stickChecking"]),  # Mitch Marner 92 RW VGK
    (897, ["strength", "defAwareness", "fighting", "faceoffs", "puckControl", "agility", "passAcc", "acceleration"]),  # Kyle Connor 92 LW WPG
    (227, ["strength", "shotBlocking", "bodyChecking", "agility", "passAcc", "deking", "stickChecking", "defAwareness"]),  # Miro Heiskanen 91 LD/RD DAL
    (450, ["bodyChecking", "strength", "slapShotPow", "fighting", "slapShotAcc", "puckControl", "agility", "acceleration"]),  # Jesper Bratt 91 LW/RW NJD
    (898, ["fighting", "strength", "bodyChecking", "stickChecking", "speed", "handEye", "deking", "slapShotAcc"]),  # Mark Scheifele 91 C WPG
    (123, ["slapShotPow", "wristShotPow", "offAwareness", "passAcc", "acceleration", "agility", "bodyChecking", "stickChecking"]),  # Jaccob Slavin 90 LD CAR
    (124, ["strength", "bodyChecking", "wristShotPow", "speed", "puckControl", "acceleration", "defAwareness", "faceoffs"]),  # Sebastian Aho 90 C CAR
    (175, ["fighting", "strength", "bodyChecking", "defAwareness", "stickChecking", "agility", "passAcc", "acceleration"]),  # Martin Necas 90 C/RW COL
    (400, ["strength", "wristShotPow", "bodyChecking", "speed", "agility", "faceoffs", "defAwareness", "deking"]),  # Nick Suzuki 90 C MTL
    (507, ["speed", "shotBlocking", "acceleration", "stickChecking", "fighting", "offAwareness", "passAcc", "deking"]),  # Adam Fox 90 RD NYR
    (525, ["fighting", "stickChecking", "acceleration", "strength", "wristShotAcc", "deking", "handEye", "offAwareness"]),  # Adam Edstrom 90 C NYR
    (535, ["strength", "defAwareness", "slapShotPow", "stickChecking", "fighting", "passAcc", "puckControl", "speed"]),  # Tim Stutzle 90 C/LW OTT
    (720, ["wristShotPow", "slapShotPow", "defAwareness", "fighting", "strength", "passAcc", "offAwareness", "acceleration"]),  # Brandon Hagel 90 LW TBL
    (775, ["wristShotPow", "slapShotPow", "defAwareness", "bodyChecking", "fighting", "acceleration", "wristShotAcc", "passAcc"]),  # Clayton Keller 90 RW/LW UTA
    (868, ["acceleration", "agility", "handEye", "passAcc", "bodyChecking", "offAwareness", "strength", "slapShotPow"]),  # Alex Ovechkin 90 LW WSH
    (899, ["fighting", "strength", "stickChecking", "bodyChecking", "wristShotPow", "acceleration", "passAcc", "offAwareness"]),  # Josh Morrissey 90 LD WPG
    (33, ["shotBlocking", "wristShotPow", "fighting", "strength", "speed", "acceleration", "passAcc", "deking"]),  # Charlie McAvoy 89 RD BOS
    (58, ["defAwareness", "bodyChecking", "fighting", "slapShotAcc", "passAcc", "deking", "wristShotAcc", "slapShotPow"]),  # Tage Thompson 89 C/RW BUF
    (94, ["puckControl", "offAwareness", "slapShotAcc", "deking", "bodyChecking", "acceleration", "fighting", "speed"]),  # Ryan Strome 89 C/RW CGY
    (176, ["slapShotPow", "wristShotPow", "strength", "deking", "offAwareness", "speed", "acceleration", "stickChecking"]),  # Devon Toews 89 LD COL
    (199, ["fighting", "bodyChecking", "strength", "wristShotPow", "slapShotPow", "stickChecking", "slapShotAcc", "speed"]),  # Kirill Marchenko 89 RW CBJ
    (229, ["acceleration", "stickChecking", "bodyChecking", "agility", "faceoffs", "passAcc", "slapShotAcc", "wristShotPow"]),  # Jason Robertson 89 LW/RW DAL
    (230, ["strength", "slapShotPow", "wristShotPow", "offAwareness", "defAwareness", "passAcc", "speed", "agility"]),  # Matt Duchene 89 C DAL
    (255, ["strength", "fighting", "bodyChecking", "slapShotAcc", "offAwareness", "defAwareness", "puckControl", "faceoffs"]),  # Dylan Larkin 89 C/LW DET
    (256, ["defAwareness", "slapShotPow", "bodyChecking", "wristShotPow", "speed", "deking", "offAwareness", "agility"]),  # Lucas Raymond 89 RW/LW DET
    (311, ["bodyChecking", "strength", "faceoffs", "acceleration", "slapShotAcc", "agility", "puckControl", "handEye"]),  # Brad Marchand 89 LW FLA
    (312, ["puckControl", "bodyChecking", "deking", "shotBlocking", "offAwareness", "fighting", "speed", "slapShotPow"]),  # Gustav Forsling 89 LD FLA
    (368, ["stickChecking", "faceoffs", "bodyChecking", "defAwareness", "speed", "slapShotAcc", "passAcc", "agility"]),  # Matt Boldy 89 LW/RW MIN
    (429, ["defAwareness", "fighting", "strength", "slapShotPow", "slapShotAcc", "passAcc", "wristShotAcc", "handEye"]),  # Filip Forsberg 89 LW NSH
    (451, ["strength", "bodyChecking", "slapShotPow", "speed", "acceleration", "defAwareness", "deking", "faceoffs"]),  # Nico Hischier 89 C NJD
    (508, ["speed", "acceleration", "wristShotAcc", "offAwareness", "defAwareness", "passAcc", "strength", "slapShotPow"]),  # J.T. Miller 89 C/LW NYR
    (536, ["speed", "defAwareness", "acceleration", "handEye", "deking", "strength", "stickChecking", "bodyChecking"]),  # Brady Tkachuk 89 LW OTT
    (537, ["wristShotPow", "fighting", "strength", "bodyChecking", "offAwareness", "agility", "acceleration", "speed"]),  # Jake Sanderson 89 LD OTT
    (692, ["fighting", "wristShotPow", "slapShotPow", "slapShotAcc", "wristShotAcc", "offAwareness", "acceleration", "passAcc"]),  # Robert Thomas 89 C/RW STL
    (721, ["speed", "faceoffs", "strength", "acceleration", "stickChecking", "agility", "handEye", "wristShotAcc"]),  # Jake Guentzel 89 LW/RW TBL
    (836, ["fighting", "strength", "wristShotPow", "slapShotPow", "puckControl", "agility", "acceleration", "shotBlocking"]),  # Alex Pietrangelo 89 D VGK
    (837, ["acceleration", "agility", "wristShotAcc", "deking", "strength", "passAcc", "offAwareness", "defAwareness"]),  # Mark Stone 89 RW VGK
    (838, ["slapShotPow", "shotBlocking", "wristShotPow", "bodyChecking", "offAwareness", "acceleration", "deking", "passAcc"]),  # Noah Hanifin 89 D VGK
    (869, ["speed", "fighting", "strength", "stickChecking", "defAwareness", "handEye", "wristShotPow", "faceoffs"]),  # Dylan Strome 89 C WSH
    (1, ["stickChecking", "shotBlocking", "fighting", "bodyChecking", "speed", "agility", "wristShotPow", "slapShotPow"]),  # John Carlson 88 RD ANA
    (125, ["defAwareness", "stickChecking", "slapShotPow", "offAwareness", "puckControl", "wristShotAcc", "deking", "speed"]),  # Nikolaj Ehlers 88 LW/RW CAR
    (126, ["bodyChecking", "faceoffs", "slapShotPow", "puckControl", "handEye", "strength", "agility", "speed"]),  # Seth Jarvis 88 RW CAR
    (147, ["faceoffs", "defAwareness", "strength", "stickChecking", "bodyChecking", "acceleration", "deking", "puckControl"]),  # Connor Bedard 88 C CHI
    (231, ["slapShotPow", "wristShotPow", "fighting", "shotBlocking", "puckControl", "deking", "stickChecking", "acceleration"]),  # Thomas Harley 88 LD DAL
    (257, ["defAwareness", "strength", "slapShotPow", "faceoffs", "speed", "agility", "passAcc", "wristShotAcc"]),  # Alex DeBrincat 88 RW/LW DET
    (258, ["stickChecking", "fighting", "speed", "wristShotPow", "agility", "deking", "puckControl", "slapShotPow"]),  # Moritz Seider 88 RD DET
]


def main():
    random.seed(42)
    players = list(PLAYER_REVEALS)
    random.shuffle(players)

    puzzles = [(date, pid, rev) for date, (pid, rev) in zip(DATES, players)]

    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    skipped = []
    inserted = []

    for date, player_id, reveal_order in puzzles:
        cur.execute("SELECT player_id, created_by FROM daily_puzzles_nhl WHERE date = ?", (date,))
        existing = cur.fetchone()
        if existing:
            ex_pid, ex_by = existing
            if ex_pid != player_id and ex_by != "seed":
                skipped.append(f"  SKIP {date}: admin-scheduled player_id={ex_pid}")
                continue
        cur.execute(
            "INSERT OR REPLACE INTO daily_puzzles_nhl (date, player_id, reveal_order_json, created_by) VALUES (?,?,?,?)",
            (date, player_id, json.dumps(reveal_order), "seed")
        )
        inserted.append(date)

    conn.commit()
    conn.close()

    print(f"Inserted/updated {len(inserted)} puzzles.")
    if skipped:
        print(f"Skipped {len(skipped)} dates (different player already scheduled):")
        for s in skipped:
            print(s)
    print(f"Date range: {puzzles[0][0]} to {puzzles[-1][0]}")
    print("Done.")


if __name__ == "__main__":
    main()
