"""
seed_puzzles_madden.py — Insert Madden daily puzzles 2026-03-17 through 2026-05-24 (69 days).
Safe to re-run: uses INSERT OR REPLACE. Player order is randomized.

Reveal order philosophy:
  Data-driven via gen_madden_reveals.py (z-score vs position-group peers).
  Slots 1-3: near-average attributes (low |z|, generic, don't give it away).
  Slots 4-6: moderately distinctive.
  Slots 7-8: highest |z| — signature stats that clinch identification.
"""

import sqlite3
import json
import os
import random

DB_PATH = os.environ.get("RATINGSCHECK_DB", "ratingscheck.db")

DATES = [
    "2026-03-17","2026-03-18","2026-03-19","2026-03-20","2026-03-21","2026-03-22","2026-03-23",
    "2026-03-24","2026-03-25","2026-03-26","2026-03-27","2026-03-28","2026-03-29","2026-03-30",
    "2026-03-31","2026-04-01","2026-04-02","2026-04-03","2026-04-04","2026-04-05","2026-04-06",
    "2026-04-07","2026-04-08","2026-04-09","2026-04-10","2026-04-11","2026-04-12","2026-04-13",
    "2026-04-14","2026-04-15","2026-04-16","2026-04-17","2026-04-18","2026-04-19","2026-04-20",
    "2026-04-21","2026-04-22","2026-04-23","2026-04-24","2026-04-25","2026-04-26","2026-04-27",
    "2026-04-28","2026-04-29","2026-04-30","2026-05-01","2026-05-02","2026-05-03","2026-05-04",
    "2026-05-05","2026-05-06","2026-05-07","2026-05-08","2026-05-09","2026-05-10","2026-05-11",
    "2026-05-12","2026-05-13","2026-05-14","2026-05-15","2026-05-16","2026-05-17","2026-05-18",
    "2026-05-19","2026-05-20","2026-05-21","2026-05-22","2026-05-23","2026-05-24",
]

# Exactly 69 players (7 QB, 10 WR, 9 HB, 7 TE, 8 DE, 7 DT, 6 LB, 10 CB/S, 4 OL, 1 K)
# Reveal orders generated by gen_madden_reveals.py using z-scores vs position-group peers.
PLAYER_REVEALS = [
    # ── QBs (7) ──
    (616, ["agility", "speed", "acceleration", "throwAccShort", "breakSack", "throwPower", "throwUnderPressure", "throwAccOnRun"]),  # Josh Allen 99
    (618, ["throwAccDeep", "throwPower", "acceleration", "agility", "throwAccShort", "playAction", "throwAccMed", "throwUnderPressure"]),  # Lamar Jackson 99
    (628, ["throwPower", "speed", "acceleration", "playAction", "breakSack", "throwUnderPressure", "throwAccShort", "throwAccMed"]),  # Joe Burrow 97
    (643, ["speed", "acceleration", "throwAccDeep", "breakSack", "awareness", "throwAccMed", "throwAccShort", "throwUnderPressure"]),  # Patrick Mahomes 95
    (717, ["agility", "speed", "acceleration", "throwAccDeep", "throwAccShort", "throwUnderPressure", "throwAccOnRun", "throwPower"]),  # Justin Herbert 88
    (734, ["throwPower", "throwUnderPressure", "acceleration", "speed", "throwAccShort", "breakSack", "throwAccDeep", "throwAccOnRun"]),  # Jalen Hurts 87
    (705, ["breakSack", "playAction", "throwUnderPressure", "speed", "throwAccShort", "agility", "throwAccDeep", "acceleration"]),  # Matthew Stafford 89
    # ── WRs (10) ──
    (615, ["acceleration", "agility", "strength", "speed", "specCatch", "release", "shortRoute", "deepRoute"]),  # Ja'Marr Chase 99
    (617, ["speed", "strength", "acceleration", "agility", "catching", "deepRoute", "shortRoute", "cit"]),  # Justin Jefferson 99
    (631, ["acceleration", "speed", "strength", "agility", "specCatch", "cit", "catching", "medRoute"]),  # Amon-Ra St. Brown 96
    (636, ["acceleration", "speed", "strength", "catching", "agility", "medRoute", "specCatch", "release"]),  # CeeDee Lamb 95
    (645, ["strength", "cit", "catching", "specCatch", "release", "acceleration", "deepRoute", "medRoute"]),  # Tyreek Hill 95
    (655, ["agility", "acceleration", "strength", "specCatch", "speed", "deepRoute", "cit", "catching"]),  # Terry McLaurin 94
    (657, ["speed", "agility", "acceleration", "deepRoute", "medRoute", "catching", "specCatch", "cit"]),  # A.J. Brown 93
    (660, ["speed", "acceleration", "agility", "deepRoute", "shortRoute", "strength", "specCatch", "cit"]),  # Mike Evans 93
    (682, ["acceleration", "agility", "deepRoute", "speed", "medRoute", "release", "specCatch", "catching"]),  # Drake London 91
    (695, ["acceleration", "agility", "strength", "speed", "release", "specCatch", "catching", "shortRoute"]),  # Puka Nacua 90
    # ── HBs (9) ──
    (621, ["trucking", "bcVision", "acceleration", "catching", "carrying", "speed", "changeDir", "agility"]),  # Saquon Barkley 99
    (622, ["agility", "jukeMoves", "catching", "acceleration", "speed", "breakTackle", "strength", "stiffArm"]),  # Derrick Henry 98
    (639, ["strength", "stiffArm", "breakTackle", "acceleration", "bcVision", "speed", "changeDir", "agility"]),  # Jahmyr Gibbs 95
    (648, ["strength", "speed", "stiffArm", "acceleration", "breakTackle", "bcVision", "changeDir", "catching"]),  # Christian McCaffrey 94
    (668, ["acceleration", "catching", "speed", "stiffArm", "bcVision", "breakTackle", "strength", "jukeMoves"]),  # Bijan Robinson 92
    (683, ["acceleration", "speed", "trucking", "breakTackle", "agility", "catching", "stiffArm", "bcVision"]),  # Joe Mixon 91
    (691, ["changeDir", "acceleration", "carrying", "agility", "catching", "trucking", "bcVision", "stiffArm"]),  # Josh Jacobs 90
    (715, ["carrying", "agility", "acceleration", "changeDir", "speed", "trucking", "bcVision", "stiffArm"]),  # Jonathan Taylor 88
    (718, ["catching", "stiffArm", "jukeMoves", "bcVision", "acceleration", "breakTackle", "changeDir", "agility"]),  # Kenneth Walker III 88
    # ── TEs (7) ──
    (623, ["acceleration", "blockShed", "agility", "strength", "catching", "medRoute", "release", "runBlock"]),  # George Kittle 98
    (663, ["blockShed", "speed", "acceleration", "agility", "strength", "deepRoute", "catching", "shortRoute"]),  # Travis Kelce 93
    (675, ["strength", "trucking", "runBlock", "blockShed", "speed", "deepRoute", "medRoute", "shortRoute"]),  # Trey McBride 92
    (678, ["runBlock", "strength", "blockShed", "acceleration", "agility", "deepRoute", "catching", "medRoute"]),  # Brock Bowers 91
    (694, ["agility", "trucking", "blockShed", "acceleration", "runBlock", "deepRoute", "shortRoute", "release"]),  # Mark Andrews 90
    (723, ["speed", "acceleration", "trucking", "agility", "blockShed", "release", "shortRoute", "catching"]),  # T.J. Hockenson 88
    (731, ["acceleration", "agility", "speed", "catching", "strength", "deepRoute", "medRoute", "runBlock"]),  # Dallas Goedert 87
    # ── DEs / Pass Rushers (8) ──
    (620, ["hitPower", "finesseMoves", "acceleration", "speed", "agility", "pursuit", "blockShed", "strength"]),  # Myles Garrett 99
    (624, ["hitPower", "tackle", "pursuit", "strength", "powerMoves", "finesseMoves", "speed", "acceleration"]),  # Micah Parsons 98
    (632, ["speed", "strength", "acceleration", "powerMoves", "agility", "finesseMoves", "hitPower", "tackle"]),  # Maxx Crosby 96
    (634, ["agility", "strength", "powerMoves", "acceleration", "finesseMoves", "hitPower", "blockShed", "tackle"]),  # T.J. Watt 96
    (642, ["hitPower", "tackle", "acceleration", "pursuit", "blockShed", "finesseMoves", "powerMoves", "speed"]),  # Nick Bosa 95
    (664, ["hitPower", "powerMoves", "tackle", "agility", "pursuit", "acceleration", "strength", "blockShed"]),  # Trey Hendrickson 93
    (667, ["tackle", "acceleration", "strength", "agility", "hitPower", "blockShed", "pursuit", "speed"]),  # Aidan Hutchinson 92
    (679, ["tackle", "powerMoves", "acceleration", "agility", "finesseMoves", "blockShed", "speed", "hitPower"]),  # Danielle Hunter 91
    # ── DTs (7) ──
    (625, ["speed", "agility", "hitPower", "tackle", "strength", "blockShed", "pursuit", "powerMoves"]),  # Chris Jones 97
    (626, ["agility", "hitPower", "speed", "finesseMoves", "tackle", "pursuit", "powerMoves", "blockShed"]),  # Dexter Lawrence II 97
    (638, ["speed", "finesseMoves", "agility", "hitPower", "powerMoves", "strength", "tackle", "blockShed"]),  # Derrick Brown 95
    (646, ["agility", "speed", "finesseMoves", "strength", "powerMoves", "pursuit", "hitPower", "blockShed"]),  # Cameron Heyward 94
    (665, ["speed", "agility", "finesseMoves", "pursuit", "powerMoves", "strength", "hitPower", "blockShed"]),  # Vita Vea 93
    (671, ["tackle", "speed", "agility", "finesseMoves", "powerMoves", "hitPower", "blockShed", "pursuit"]),  # Jeffery Simmons 92
    (686, ["strength", "tackle", "hitPower", "finesseMoves", "agility", "powerMoves", "pursuit", "blockShed"]),  # Quinnen Williams 91
    # ── LBs (6) ──
    (627, ["agility", "tackle", "strength", "hitPower", "speed", "playRecog", "zoneCoverage", "acceleration"]),  # Fred Warner 97
    (653, ["playRecog", "manCoverage", "zoneCoverage", "hitPower", "speed", "acceleration", "pursuit", "agility"]),  # Roquan Smith 94
    (677, ["strength", "pursuit", "agility", "playRecog", "awareness", "acceleration", "speed", "manCoverage"]),  # Bobby Wagner 91
    (688, ["zoneCoverage", "acceleration", "manCoverage", "tackle", "playRecog", "hitPower", "speed", "strength"]),  # Demario Davis 90
    (721, ["playRecog", "speed", "agility", "zoneCoverage", "strength", "acceleration", "awareness", "tackle"]),  # Lavonte David 88
    (726, ["acceleration", "hitPower", "speed", "tackle", "agility", "pursuit", "zoneCoverage", "playRecog"]),  # Zack Baun 88
    # ── CBs / Safeties (10) ──
    (629, ["hitPower", "acceleration", "strength", "agility", "pursuit", "awareness", "pressing", "manCoverage"]),  # Patrick Surtain II 97
    (637, ["tackle", "strength", "pursuit", "acceleration", "pressing", "zoneCoverage", "awareness", "manCoverage"]),  # Christian Gonzalez 95
    (640, ["speed", "acceleration", "strength", "agility", "pressing", "manCoverage", "awareness", "pursuit"]),  # Jessie Bates III 95
    (650, ["speed", "acceleration", "agility", "zoneCoverage", "pressing", "hitPower", "awareness", "strength"]),  # Derwin James Jr 94
    (651, ["acceleration", "pursuit", "tackle", "agility", "hitPower", "zoneCoverage", "awareness", "pressing"]),  # Jalen Ramsey 94
    (654, ["hitPower", "pursuit", "strength", "tackle", "acceleration", "awareness", "zoneCoverage", "manCoverage"]),  # Sauce Gardner 94
    (658, ["hitPower", "pursuit", "tackle", "strength", "acceleration", "agility", "awareness", "manCoverage"]),  # Derek Stingley Jr 93
    (666, ["agility", "acceleration", "pressing", "speed", "strength", "awareness", "zoneCoverage", "pursuit"]),  # Xavier McKinney 93
    (669, ["speed", "acceleration", "pressing", "agility", "manCoverage", "strength", "tackle", "pursuit"]),  # Budda Baker 92
    (672, ["agility", "acceleration", "speed", "hitPower", "pursuit", "zoneCoverage", "strength", "pressing"]),  # Marlon Humphrey 92
    # ── OL (4) ──
    (619, ["strength", "speed", "agility", "impactBlock", "runBlockFin", "passBlockPow", "runBlock", "runBlockPow"]),  # Lane Johnson 99 RT
    (630, ["agility", "speed", "passBlockFin", "strength", "passBlock", "runBlockFin", "runBlock", "impactBlock"]),  # Trent Williams 97 LT
    (633, ["agility", "speed", "passBlockFin", "passBlock", "passBlockPow", "strength", "runBlockFin", "runBlock"]),  # Penei Sewell 96 RT
    (635, ["agility", "runBlockPow", "speed", "runBlock", "runBlockFin", "impactBlock", "passBlockPow", "passBlockFin"]),  # Tristan Wirfs 96 LT
    # ── K (1) ──
    (728, ["strength", "acceleration", "stamina", "awareness", "kickPower", "agility", "speed", "kickAcc"]),  # Brandon Aubrey 87
]


def main():
    assert len(PLAYER_REVEALS) == len(DATES), f"{len(PLAYER_REVEALS)} players != {len(DATES)} dates"

    random.seed(42)
    players = list(PLAYER_REVEALS)
    random.shuffle(players)

    puzzles = [(date, pid, rev) for date, (pid, rev) in zip(DATES, players)]

    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    skipped = []
    inserted = []

    for date, player_id, reveal_order in puzzles:
        cur.execute("SELECT player_id, created_by FROM daily_puzzles_madden WHERE date = ?", (date,))
        existing = cur.fetchone()
        if existing:
            ex_pid, ex_by = existing
            if ex_pid != player_id and ex_by != "seed":
                # Admin-scheduled — preserve it
                skipped.append(f"  SKIP {date}: admin-scheduled player_id={ex_pid}")
                continue
        cur.execute(
            "INSERT OR REPLACE INTO daily_puzzles_madden (date, player_id, reveal_order_json, created_by) VALUES (?,?,?,?)",
            (date, player_id, json.dumps(reveal_order), "seed")
        )
        inserted.append(date)

    conn.commit()
    conn.close()

    print(f"Inserted/updated {len(inserted)} puzzles.")
    if skipped:
        print(f"Skipped {len(skipped)} dates (different player already scheduled):")
        for s in skipped:
            print(s)
    print(f"Date range: {puzzles[0][0]} to {puzzles[-1][0]}")
    print("Done.")


if __name__ == "__main__":
    main()
